# Generated by Django 4.2.3 on 2025-11-06 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_vat_number_alter_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
