# Generated by Django 4.2.3 on 2025-11-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(max_length=9),
        ),
    ]
