# Generated by Django 4.2.3 on 2025-11-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
