# Generated by Django 4.2.3 on 2025-11-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
